version: '3.8'

services:
  # Serviços de Infraestrutura
  config-server:
    # CORREÇÃO: Usa a variável IMAGE_TAG
    image: ${CI_REGISTRY}/${CI_PROJECT_PATH_LOWER}/config-server:${IMAGE_TAG}
    # ... (o resto do serviço continua igual)

  discovery-server:
    image: ${CI_REGISTRY}/${CI_PROJECT_PATH_LOWER}/discovery-server:${IMAGE_TAG}
    # ...

  api-gateway:
    image: ${CI_REGISTRY}/${CI_PROJECT_PATH_LOWER}/api-gateway:${IMAGE_TAG}
    # ...

  # Serviços de Aplicação
  property-service:
    image: ${CI_REGISTRY}/${CI_PROJECT_PATH_LOWER}/property-service:${IMAGE_TAG}
    # ...

  auth-backend:
    image: ${CI_REGISTRY}/${CI_PROJECT_PATH_LOWER}/auth-backend:${IMAGE_TAG}
    # ...

  auth-frontend:
    image: ${CI_REGISTRY}/${CI_PROJECT_PATH_LOWER}/auth-frontend:${IMAGE_TAG}
    # ...
  
  # Banco de Dados
  auth-db:
    image: mysql:8.0
    # ... (o resto do ficheiro continua igual)